### ISSUE TITLE
Django-revproxy doesn't include requesting user information by default

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/django_docker_engine#125]
Before the [switch to django-revproxy](https://github.com/refinery-platform/django_docker_engine/pull/116), information about the requesting Django User was passed through to the proxied request. Now this isn't the case unless the [`ProxyView` is instantiated with `add_remote_user=True`](http://django-revproxy.readthedocs.io/en/0.9.3/introduction.html?highlight=REMOTE_USER).

I've started this work here: https://github.com/refinery-platform/django_docker_engine/pull/119, but got hung up while updating tests. Specifically the doctests were getting lengthier and less straightforward for an end user to look at.

**Comment by mccalluc** [comment]
Fixed in #126
