### ISSUE TITLE
deconstructibility?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/django_docker_engine#27]
@scottx611x : what's the status of https://github.com/refinery-platform/django_docker_engine/compare/scottx611x/add_deconstrucibility?expand=1? Can the branch be deleted? If it's work that could be integrated, is the migration necessary? In my mind, nothing here would necessarily depend on the database, but I could be thinking about it wrong.

**Comment by scottx611x** [comment]
@mccalluc Lets delete that implementation and we can start fresh after lunchtime
