### ISSUE TITLE
Make a tag for refinery dependencies?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/django_docker_engine#32]
@scottx611x : I'm trying to remember if the github dependency you have in refinery works with tags: I'll probably be changing the interfaces here soon, and I want to make sure that doesn't trip you up...

**Comment by scottx611x** [comment]
@mccalluc The `pip install -e` can work with a bunch of stuff, tags included! Would be great to pin something  less variable than `@master`

**Comment by mccalluc** [comment]
Awesome: here's a tag. Close this when it's pinned on the Refinery end? https://github.com/refinery-platform/django_docker_engine/releases/tag/v0.0.1
