### ISSUE TITLE
Remove tests that hit AWS?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/django_docker_engine#54]
@hackdna : Would it be ok if I kept the tests that hit AWS around at least for PR builds? What happens inside the docker engine should work anywhere, but there are also operations that happen on the host, and for those there are differences between local and remote that I don't have a handle on. (Spent pretty much all of Monday and Tuesday trying to understand why paramiko from travis to ec2 was different than local to ec2, and never got to the root of it: just used a subprocess ssh instead.)

**Comment by hackdna** [comment]
A few questions:
1. This is additional code that would have to be maintained. Is it worth the effort?
1. How often these tests would run and how much would they cost?
1. What happens in case of failures? What ensures that test resources get cleaned up after each run?
1. What ensures that the tests are self-contained and won't affect other resources in the account?
1. Are there any other implications and/or pitfalls? Any examples of projects that use this type of approach?

**Comment by mccalluc** [comment]
1. I think so: It took a fair bit of effort to get the stack build to work, and (at least when I tried to use paramiko), the behavior on travis was different than locally in a way that I still don't understand: The code is complicated, and somewhat fragile, and those factors argue in favor of testing.
2. An hour of t2.nano is $0.0065. Any developer time we save will dominate this.
3. There is an [after script section](https://github.com/refinery-platform/django_docker_engine/blob/master/.travis.yml#L53-L54) which removes the stack. (And even if it's missed, it would take a while for the costs to even be noticeable.)
4. Code reviews? The travis-ci user's credentials could be restricted, but you'd still need to trust that they had been restricted appropriately. I would be glad to have a separated isolated account, alternatively.
5. I'm not sure about other examples: There a lots of instances of folks using travis as part of a deployment process to AWS.

Another possibility would be to split the AWS part off into a separate project, but I'm not sure that would be worth the trouble.

**Comment by hackdna** [comment]
Sounds good. I think it would be great to find some examples of using Travis with AWS to avoid re-inventing the wheel and learn about best practices.

**Comment by mccalluc** [comment]
Actually, I just went ahead and took out the AWS stuff: ba0bd1590d2da9fd650c3eb4d9ee7d2ad3ddaec6. I still think it would be good to have in place, but I wasn't actually cleaning up old instances consistently at the end of tests, and particularly with the security concerns, I need to make it simpler for now do it doesn't suck up any more time.
