### ISSUE TITLE
Placeholder for 8-4 mtg. takeaways

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/django_docker_engine#65]
- Implement db models & understand how this works when integrated as a Django app Refinery-side

**Comment by mccalluc** [comment]
The topics in:

<img width="461" alt="screen shot 2017-08-04 at 11 38 17 am" src="https://user-images.githubusercontent.com/730388/28975740-247e53bc-7909-11e7-9780-31628a5b4767.png">

are covered by:

- #66 
- #67 
- #68 
- #69
- #70
- #71
- #72 

Closing.
