### ISSUE TITLE
Stop clobbering Django csrf on POSTs

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/django_docker_engine#95]
At first we saw this trying to use [dash](https://github.com/refinery-platform/heatmap-scatter-dash/issues/53) ... But I think I convinced myself that the problem was in the proxy layer.

@scottx611x : Did you have other thoughts on this right now?

**Comment by mccalluc** [comment]
@scottx611x : Have we had any more trouble with this? If it were still a problem, I don't think it would have fallen off the radar, so I'm inclined to close...

**Comment by scottx611x** [comment]
@mccalluc I thought we fixed this by not clobbering CSRF by default let me check
